return {
    ["discord_link"] = "B2tznpnRvy",
    ["names"] = {
        ["logo"] = "39y48htoin34o0h30h4jg03nrognwogolhsoey02up4j6pj23-04jg0uw0e3jg0ijw4hgo3herhgoejrogjerjg0jer0gje0rjgoehrogheorhgoejrgojerojgeojrgojerojgeoirgoh",
        ["close"] = "8735yth34b083b40234-939f29j3-9f2-9i3f-9i2-eigf-iwr-hudpjfhjdlfjhljdgfohjdojfhojdofjhodjfohjdofjhojdgphkfpgk"
    },
    ["ggKey"] = "-eiu4ty-juehje-4jhy-w4-0yh304y0bjpoekr;gjpeuj50-y9u54-iy-043i5-hje[prthmjpiejur09huw-eir=-qiw3t=jm35-jhe-0urh0jdrp[ohme;mhpjue-50uy-ejbmer[kh[eir-hie-u[erktj[mrtpohj-"
};
